[gcp_service_account]
type = "service_account"
project_id = "sidc-464820"
private_key_id = "3b44980214bd248ff8a0f2ec43a594f039a24a90"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCeEFVsYS4MfHOF
hKKyZdCzneyCD4pBdM2Ap8tYbEMjMHWGcimByojeZDWo/pgQEGicdGAantWcyt85
RM4gGNeae28lq0PFsxSXcBKbyWp+hXoP+dEDOYBTuWElBI/ZW2NRw+lrNvlrB0YW
Pow0+b1Tf8RYgr+fiXmWFyXfmEbLH8rs+qywoWQi385G+QyKcJh6f94qTd2C4U0s
7FPuoX3JkFQjlRzcpAPmXEHd//e+hKHoOfQgIvMDdrRmY3mmNpllF189S1bAjrpe
Tn6p+ZL7ez6wnECBjv8Hd5ewvEgvNBGixSErofJB+NIlojgXiStgFGJB72vqTZM0
02hpZ3shAgMBAAECggEAQRgN7e/JhIfeFU7tp9VpUQdJBrj6oYFGPmUbx6LyNTQ4
OjGaqWJs4lVXieyrV/ZB9qiwiVX/N66OpmmRD8PbSrnpqJQy+WCKKuGTMEgPDOLQ
RXMGojLUh+ZQvOt3iDZsHRi28Jn3tp2Mvg1tNUXiM9hq1l6mJr/5bBfFV6NBCFY9
6yvm74tlPD6e4272TPH0GJBIUss3y7f/oJBuUAmm+wK4iDA3NKYcfyScH4eFK09r
VRL0CmcxFF8dKi4Aw7ln6hnFO8gwXC4ydV+JvktqO7ejt4APTOZr18dbS6ORGIkf
mdQxwl9rZ1eZnqx4Yg/WKS4dDnDkwEYsFRPcmxGyFwKBgQDXcpc1zXy5NWnHvuhc
6mLFCeUl75Y/1He9PR2Cj2/qcjVy1FjuhKlgnELLIVu2QhxrdeQdc8nmzOlp7vil
LUcsk80cPk4CJTKScKgWDM7KlGb1EkYeh/2o1VSrZZvFE6neCvu411qHLf3iTpjs
4VTlYgB8JSNAAlwudFzjrh7AfwKBgQC70K+yGVVnknKMRZqga95ydpwRTwFxYtr9
+6xcAeSi7H92yYP6403AEd2ZsqlwBF8U9F1jPqxhPNCmRBKOiAZIc4qpr87gIo0z
1N/zByJJ4PNesq31Mh2/hGxRjWzGghsMW6NzqJrthm2hxQrF36eYw8FsTuOi0LWx
/LfRQPv0XwKBgQCa/slh348W/yI2nVU1YznjXxcHj7GcAhKSheExCFgPZlKlZbcF
AVOJOWGkGT+Ng0pG1O1jcuWRsWFK4KzoyAYoP7yT0Q715CTZzUpfcp9ihhj7vkXL
uTH3wGHFXLgPs/HE2En31JZAIgpAQSMrZ4BX9YU7ysvtRMVkdjpNYfqlqQKBgGTd
/g4bdvep+iUFmLbBV/WHZ+gP00mO+ufey0Garq0lcIteTKhofTBDKA1Mm50Sa/I4
DxOm7DNI0xIIiyLLQPyWOQlK50MOq2ED2caOtUaSLoJUWgLOiJV7zCS8XIf8BgTM
DmumSJZ6VNTFmzSMGll8AJxnfe/KQVq2zA3w5Z/nAoGBAMW6elDhvGEQXtq6NZoJ
LOnFLhnz8e4Kcrey7xpObFaktqSdYOzpPb9FFWPO+xDFsLMPQqrukpZiuuIEEuno
D0R9d/FKZyRxHIXiwmx4XVcgLpvUhFI4M1v6tPtsaapF9YDrPr8DFhqnXNWSRiHJ
TmV/hFL1m97LJWRA+H7/J9Uu
-----END PRIVATE KEY-----"""
client_email = "id-025sidc@sidc-464820.iam.gserviceaccount.com"
client_id = "112165191520766743022"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/id-025sidc%40sidc-464820.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
